name: Build & deploy

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    
    - name: Install NPM packages
      run: yarn install
    
    - name: Build project
      run: yarn build
